# This job will only run for pull requests created by Dependabot.
# It will auto-approve and rebase-merge Dependabot PRs for minor/patch updates
# once all checks and branch protection rules pass.

name: Dependabot Auto Merge

on: [push, pull_request]

jobs:
  auto-merge:
    if: ${{ github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.MYTOKEN}} 
